spring:
  application:
    name: eureka-client-b
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'

#端口号
server:
  port: 8002

#eureka配置信息
eureka:
  client:
    #ָ注册中心地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/